name: Check User Permission

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@dd299b8721172b30ae80fa66177e99b749e705e0 # main
        id: checkUser
        with:
          require: 'write'

      - name: close
        if: steps.checkUser.outputs.check-result == 'false'
        uses: actions-cool/issues-helper@a610ededc35d20c08d8b6d3d68d7f3183a7a8ef7 # v2.1.2
        with:
          actions: 'close-issue'
          issue-number: ${{ github.event.issue.number }}
